### ISSUE TITLE
error

### ISSUE THREAD

**Issue by glaye** [FuLygon/Navicat-Linux#5]
[+] Try to open libcc.dll ... OK!
[-] .\navicat-patcher\elf64_interpreter.cpp:414 ->
    Unsupported ELF file: unhandled relocation type(16).

**Comment by FuLygon** [comment]
can I get more information on the version of Navicat you currently using

**Comment by carlosmrivera** [comment]
Same error here. Ubuntu 22.04. Navicat 15.0.30 Appimage.
![Screenshot from 2024-07-02 01-33-20](https://github.com/FuLygon/Navicat-Linux/assets/100056053/65011039-9a34-4033-93ad-9223442f2da7)

**Comment by carlosmrivera** [comment]
> can I get more information on the version of Navicat you currently using

Ubuntu 22.04
Navicat 15.0.30

**Comment by FuLygon** [comment]
> > can I get more information on the version of Navicat you currently using
> 
> Ubuntu 22.04 Navicat 15.0.30

you are using Navicat `15.0.30`, and using navicat-patcher version `16.0.7.0-3`, as mentioned in the [README](https://github.com/FuLygon/Navicat-Linux/blob/master/README.md), please use branch [15](https://github.com/FuLygon/Navicat-Linux/tree/15) for Navicat version 15

**Comment by FuLygon** [comment]
I'm closing this issue as this issue most likely related to using the wrong version of navicat-patcher for Navicat 15, please refer to [README](https://github.com/FuLygon/Navicat-Linux/blob/master/README.md) for futher information on patching Navicat 15

**Comment by carlosmrivera** [comment]
> I'm closing this issue as this issue most likely related to using the wrong version of navicat-patcher for Navicat 15, please refer to [README](https://github.com/FuLygon/Navicat-Linux/blob/master/README.md) for futher information on patching Navicat 15

Now, using the branch 15, I got a similar error. See details below:

![carbon](https://github.com/FuLygon/Navicat-Linux/assets/100056053/386fcdba-94c0-4d3e-8da6-9493f0888560)

**Comment by FuLygon** [comment]
> > I'm closing this issue as this issue most likely related to using the wrong version of navicat-patcher for Navicat 15, please refer to [README](https://github.com/FuLygon/Navicat-Linux/blob/master/README.md) for futher information on patching Navicat 15
> 
> Now, using the branch 15, I got a similar error. See details below:
> 
> ![carbon](https://private-user-images.githubusercontent.com/100056053/345719262-386fcdba-94c0-4d3e-8da6-9493f0888560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTY5NjAsIm5iZiI6MTcyMjQ5NjY2MCwicGF0aCI6Ii8xMDAwNTYwNTMvMzQ1NzE5MjYyLTM4NmZjZGJhLTk0YzAtNGQzZS04ZGE2LTk0OTNmMDg4ODU2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQwNzE3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2NkN2U2ZDQ3Yjg5ZmY1ZWQ3MWZjYTViNjcwMjFiYmE2NDRlZDZmMWFmYzg4MzM3YjBmNWZlZTJmOGI3YTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZMC4RQoDql2mQbq6oMzOD-s5h-wIQbLnQ75NUxuEOIs)

sorry for really late response, been busy, weird I can't seem to replicate the same error, the script seem to patch Navicat `15.0.30` normally on my side, since I don't actually code the patcher, currently I can't figuring out what's causing the issue, have you tried running the script again or on different machine ?
